name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Modules
        run: |
          cd api
          npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build API image (multi-arch)
      - name: Build API Nginx Image
        run: |
          cp -r ./shared ./api/shared

          docker buildx build \
            --file ./api/Dockerfile \
            --platform linux/amd64,linux/arm64/v8,linux/arm/v7 \
            --tag joehannis/taplist-keg-level-manager:api-nginx \
            ./api \
            --push

      - name: Build Frontend Nginx Image
        run: |
          cp -r ./shared ./frontend/shared

          docker buildx build \
            --file ./frontend/Dockerfile \
            --platform linux/amd64,linux/arm64/v8,linux/arm/v7 \
            --tag joehannis/taplist-keg-level-manager:frontend-nginx \
            ./frontend \
            --push
