name: Docker Image CI

on:
  push:
    branches:
      - 'nginx-serve'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Modules
        run: |
          cd api
          npm install
      # - name: Run Jest Tests
      #   run: |
      #     cd api
      #     npm run test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build the image
        run: |
          cp -r ./shared ./api/shared

          docker buildx build \
            --file ./api/Dockerfile \
            --tag joehannis/taplist-keg-level-manager:api-nginx \
            --platform linux/amd64,linux/arm64,linux/arm64/v8 ./api \
            --build-arg NODE_VERSION=24 \
            --push

          docker buildx build \
            --file ./api/Dockerfile \
            --tag joehannis/taplist-keg-level-manager:api-nginx \
            --platform linux/arm/v7,linux/arm/v8 ./api \
            --build-arg NODE_VERSION=22 \
            --push

          docker buildx build \
            --file ./frontend/Dockerfile \
            --tag joehannis/taplist-keg-level-manager:frontend-nginx \
            --platform linux/arm64,linux/amd64,linux/arm64/v8 ./frontend \
            --build-arg NODE_VERSION=24 \
            --push

          docker buildx build \
            --file ./frontend/Dockerfile \
            --tag joehannis/taplist-keg-level-manager:frontend-nginx \
            --platform linux/arm/v7,linux/arm/v8 ./frontend \
            --build-arg NODE_VERSION=22 \
            --push
